services:
  - type: web
    name: poultry-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poultry_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
